ElectJournal.Web/Controllers/AdminController.cs
using ElectJournal.Core.Interfaces;
using ElectJournal.Web.Interfaces;
using ElectJournal.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectJournal.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IUserDeleteViewModelService UserViewModelService;
        private readonly ISubjService SubjService;
        private readonly ITimetableService TimetableService;
        private readonly IGroupService GroupService;
        private readonly ISubjViewModelService SubjViewModelService;
        private readonly IGroupViewModelService GroupViewModelService;
        private readonly ITimetableViewModelService TimetableViewModelService;
        private readonly ILogger<AdminController> Logger;
        public AdminController(ILogger<AdminController> logger, IUserDeleteViewModelService userViewModelService, ISubjService subjService, ISubjViewModelService subjViewModelService, IGroupService groupService, IGroupViewModelService groupViewModelService, ITimetableService timetableService, ITimetableViewModelService timetableViewModelService)
        {
            this.UserViewModelService = userViewModelService;
            this.SubjService = subjService;
            this.SubjViewModelService = subjViewModelService;
            this.GroupService = groupService;
            this.GroupViewModelService = groupViewModelService;
            this.TimetableViewModelService = timetableViewModelService;
            this.TimetableService = timetableService;
            this.Logger = logger;
        }

        [HttpGet]
        public IActionResult Users()
        {
            var models = UserViewModelService.List();
            return View(models);
        }

        [HttpPost]
        public IActionResult Users(int id)
        {
            try
            {
                UserViewModelService.Delete(id);
                return RedirectToAction(nameof(Users));
            }
            catch(Exception ex)
            {
                Logger.LogError(ex, "Нельзя удалить данного пользователя!");
                return RedirectToAction("Error", "Home", new { });
            }
        }

        [HttpGet]
        public IActionResult Subjects()
        {
            var models = SubjViewModelService.List();
            return View(models);
        }

        [HttpPost]
        public IActionResult Subjects(int id)
        {
            SubjViewModelService.Delete(id);
            return RedirectToAction(nameof(Subjects));
        }

        [HttpGet]
        public IActionResult SubjectsAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SubjectsAdd(SubjectViewModel subjectViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var id = SubjViewModelService.Add(subjectViewModel);
            return RedirectToAction(nameof(Subjects));
        }

        [HttpGet]
        public IActionResult SubjectsUpdate(int id)
        {
            var s = SubjViewModelService.Get(id);
            return View(s);
        }

        [HttpPost]
        public IActionResult SubjectsUpdate(SubjectViewModel subject)
        {
            SubjViewModelService.Update(subject);
            return RedirectToAction(nameof(Subjects));
        }

        [HttpGet]
        public IActionResult Groups()
        {
            var models = GroupViewModelService.List();
            return View(models);
        }

        [HttpPost]
        public IActionResult Groups(int id)
        {
            GroupViewModelService.Delete(id);
            return RedirectToAction(nameof(Groups));
        }

        [HttpGet]
        public IActionResult GroupsUpdate(int id)
        {
            var s = GroupViewModelService.Get(id);
            return View(s);
        }

        [HttpPost]
        public IActionResult GroupsUpdate(GroupViewModel group)
        {
            GroupViewModelService.Update(group);
            return RedirectToAction(nameof(Groups));
        }

        [HttpGet]
        public IActionResult GroupsAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GroupsAdd(GroupViewModel group)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var id = GroupViewModelService.Add(group);
            return RedirectToAction(nameof(Groups));
        }

        [HttpGet]
        public IActionResult TimetableAdd()
        {
            var selests = TimetableViewModelService.Get();
            return View(selests);
        }

        [HttpPost]
        public IActionResult TimetableAdd(TimetableViewModel timetable)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            TimetableViewModelService.Add(timetable);
            return RedirectToAction(nameof(TimetableAdd));
        }

        [HttpGet]
        public IActionResult _TimetablePartial()
        {
            var selests = TimetableViewModelService.Get();
            return View(selests);
        }

        [HttpGet]
        public IActionResult TimetableList(DayOfWeek dayOfWeek, int groupId, DateTime beginDate, DateTime endDate)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var selests = TimetableViewModelService.Search(dayOfWeek, groupId, beginDate, endDate);
            return View(selests);
        }

        [HttpPost]
        public IActionResult TimetableList(int id)
        {
            TimetableViewModelService.Delete(id);
            return Redirect(HttpContext.Request.Headers["Referer"]);
        }

        [HttpGet]
        public IActionResult TimetableUpdate(int id)
        {
            var item = TimetableViewModelService.Get(id);
            return View(item);
        }

        [HttpPost]
        public IActionResult TimetableUpdate(TimetableViewModel timetableViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var DayOfWeek = timetableViewModel.DayOfWeek;
            var BeginDate = timetableViewModel.BeginDate;
            var EndDate = timetableViewModel.EndDate;
            var GroupId = timetableViewModel.GroupId;
            TimetableViewModelService.Update(timetableViewModel);
            return RedirectToAction(nameof(TimetableList), new { DayOfWeek, GroupId, BeginDate, EndDate });
        }
    }
}

ElectJournal.Web/Controllers/StudentController.cs
using ElectJournal.Core.Interfaces;
using ElectJournal.Web.Interfaces;
using ElectJournal.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectJournal.Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IMarkViewModelService markViewModelService;
        private readonly IMarkService markService;
        private readonly ITimetableViewModelService timetableViewModelService;
        private readonly ILessonsViewModelService lessonsViewModelService;

        public StudentController(ILessonsViewModelService lessonsViewModelService, ITimetableViewModelService timetableViewModelService, IMarkViewModelService markViewModelService, IMarkService markService)
        {
            this.markService = markService;
            this.markViewModelService = markViewModelService;
            this.timetableViewModelService = timetableViewModelService;
            this.lessonsViewModelService = lessonsViewModelService;
        }

        [HttpGet]
        public IActionResult Marks(int userId)
        {
            var items = markViewModelService.List(userId);
            return View(items);
        }

        [HttpGet]
        public IActionResult ListOfSortedMarks(int userId, DateTime beginDate, DateTime endDate, int subjectId)
        {
            var items = markViewModelService.Filter(userId, beginDate, endDate, subjectId);
            return View(items);
        }

        [HttpPost]
        public IActionResult MarksFilter(int userId)
        {
            var items = markViewModelService.GetForFilter(userId);
            return View(items);
        }

        [HttpGet]
        public IActionResult Timetable(int groupId)
        {
            var timetableDictionary = timetableViewModelService.StudTimetable(groupId);
            return View(timetableDictionary);
        }

        [HttpGet]
        public IActionResult TimetableInfo(int id)
        {
            var item = lessonsViewModelService.GetLessonInfo(id);
            return View(item);
        }

        [HttpPost]
        public IActionResult TimetableLessons(int groupId)
        {
            var timetableDictionary = lessonsViewModelService.StudLessons(groupId);
            return View(timetableDictionary);
        }
    }
}

ElectJournal.Web/Controllers/TeacherController.cs
using ElectJournal.Core.Interfaces;
using ElectJournal.Web.Interfaces;
using ElectJournal.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ElectJournal.Web.Controllers
{
    public class TeacherController : Controller
    {
        private readonly IMarkViewModelService markViewModelService;
        private readonly IMarkService markService;
        private readonly ILessonsService lessonsService;
        private readonly ILessonsViewModelService lessonsViewModelService;
        private readonly ITimetableService timetableService;
        private readonly ITimetableViewModelService timetableViewModelService;

        public TeacherController(ITimetableViewModelService timetableViewModelService, ITimetableService timetableService, IMarkViewModelService markViewModelService, IMarkService markService, ILessonsService lessonsService, ILessonsViewModelService lessonsViewModelService)
        {
            this.markService = markService;
            this.markViewModelService = markViewModelService;
            this.lessonsViewModelService = lessonsViewModelService;
            this.lessonsService = lessonsService;
            this.timetableService = timetableService;
            this.timetableViewModelService = timetableViewModelService;
        }

        [HttpGet]
        public IActionResult LessonStart(int teacherId)
        {
            var rigthLesson = lessonsViewModelService.GetLesson(teacherId);
            if(rigthLesson == null)
            {
                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier, ErrorMessage = "Lessons not found!" });
            }
            return View(rigthLesson);
        }

        [HttpPost]
        public IActionResult LessonStart(LessonsViewModel lessonsViewModel)
        {
            var item = lessonsViewModelService.Add(lessonsViewModel);
            return RedirectToAction(nameof(Lessons), new { lessonsViewModel.TeacherId });
        }

        [HttpGet]
        public IActionResult LessonStartFromTimetable(int id)
        {
            var lesson = lessonsViewModelService.GetLessonFromTimetable(id);
            return View(lesson);
        }

        [HttpPost]
        public IActionResult LessonStartFromTimetable(LessonsViewModel lessonsViewModel)
        {
            var item = lessonsViewModelService.Add(lessonsViewModel);
            var id = lessonsViewModelService.GetById(item);
            return RedirectToAction(nameof(Lessons), new { id.TeacherId });
        }

        [HttpGet]
        public IActionResult UpdateStartLesson(int id)
        {
            var item = lessonsViewModelService.Get(id);
            return View(item);
        }

        [HttpPost]
        public IActionResult UpdateStartLesson(LessonsViewModel lessonsViewModel)
        {
            lessonsViewModelService.Update(lessonsViewModel);
            return RedirectToAction(nameof(Index), "Home");
        }

        [HttpGet]
        public IActionResult Marks()
        {
            var selects = markViewModelService.Selects(0, 0, 0);
            return View(selects);
        }

        [HttpGet]
        public IActionResult MarksList(int groupId, int subjectId, int teacherId)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var items = markViewModelService.Search(groupId, subjectId, teacherId);
            return View(items);
        }


        [HttpPost]
        public IActionResult MarksList(int id) 
        {
            markViewModelService.Delete(id);
            return Redirect(HttpContext.Request.Headers["Referer"]);
        }

        [HttpGet]
        public IActionResult Lessons(int teacherId, int id)
        {
            var items = lessonsViewModelService.SearchFive(teacherId);
            if(id != 0)
            {
                markViewModelService.Delete(id);
                return RedirectToAction(nameof(Marks));
            }
            return View(items);
        }

        [HttpPost]
        public IActionResult Lessons(int id)
        {
            lessonsViewModelService.Delete(id);
            return Redirect(HttpContext.Request.Headers["Referer"]);
        }

        [HttpGet]
        public IActionResult AllLessons(int teacherId)
        {
            var items = lessonsViewModelService.SearchAll(teacherId);
            return View(items);
        }

        [HttpGet]
        public IActionResult MarksAdd(int groupId, int lessonId, int teacherId)
        {
            var select = markViewModelService.Selects(groupId, lessonId, teacherId);
            return View(select);
        }

        [HttpPost]
        public IActionResult MarksAdd(MarksViewModel marksViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            markViewModelService.Add(marksViewModel);
            return RedirectToAction(nameof(Lessons), new { marksViewModel.TeacherId});
        }
        
        [HttpGet]
        public IActionResult Timetable(int userId)
        {
            var timetableDictionary = timetableViewModelService.TeachTimetable(userId);
            return View(timetableDictionary);
        }
    }
}

ElectJournal.Web/Views/Shared/_Layout.cshtml
@using System.Security.Claims

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElectJournal.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
            @if (User.IsInRole("admin"))
                {
                  <div id="header">
                      <div class="logo">
                            <a asp-area="" asp-controller="Home" asp-action="Index">Электронный журнал</a>
                      </div>
                        <nav>
                            <ul>
                                <li>
                                    <a asp-area="" asp-controller="Admin" asp-action="Users" class="menu">Пользователи</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Admin" asp-action="TimetableAdd" class="menu">Расписание</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Admin" asp-action="Groups" class="menu">Группы</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Admin" asp-action="Subjects" class="menu">Учебные предметы</a>
                                </li>
                            </ul>
                            <partial name="_LoginPartial" />
                        </nav>
                    </div>
                }
                else if (User.IsInRole("student"))
                {
                    <div id="header">
                        <div class="logo">
                            <a asp-area="" asp-controller="Home" asp-action="Index">Электронный журнал</a>
                        </div>
                        <nav>
                            <ul>
                                <li>
                                    <a asp-area="" asp-controller="Student" asp-action="Timetable" asp-route-groupId="@User.FindFirst(m => m.Type == ClaimTypes.Version).Value" class="menu">Расписание</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Student" asp-action="Marks" asp-route-UserId="@User.FindFirst(m => m.Type == ClaimTypes.NameIdentifier).Value" class="menu">Оценки</a>
                                </li>
                            </ul>
                            <partial name="_LoginPartial" />
                        </nav>
                    </div>
                }
                else if (User.IsInRole("teacher"))
                {
                    <div id="header">
                        <div class="logo">
                            <a asp-area="" asp-controller="Home" asp-action="Index">Электронный журнал</a>
                        </div>
                        <nav>
                            <ul>
                                <li>
                                    <a asp-area="" asp-controller="Teacher" asp-action="Timetable" asp-route-userId="@User.FindFirst(m => m.Type == ClaimTypes.NameIdentifier).Value"  class="menu">Расписание</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Teacher" asp-action="LessonStart" asp-route-TeacherId="@User.FindFirst(m => m.Type == ClaimTypes.NameIdentifier).Value" class="menu">Начать урок</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="Teacher" asp-action="Marks" class="menu">Оценки</a>
                                </li>
                            </ul>
                            <partial name="_LoginPartial" />
                        </nav>
                    </div>
                }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container" style="color:white">
            &copy; 2021 - 2022 y.: Electronic Journal. 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>